### ISSUE TITLE
galpy reference in Contigiani, Rossi, & T. Marchetti

### ISSUE THREAD

**Issue by jobovy** [contigiani/hvs#1]
Hi Omar,

I noticed that you use ``galpy`` in your recent paper, but you are referencing the wrong paper for the code. The correct reference is [Bovy (2015)](http://adsabs.harvard.edu/abs/2015ApJS..216...29B), not the Bovy, Bird, et al. (2015) paper that you cite.

Hope you are not having any issues with using the code. If there is any issue, please don't hesitate to ask me!

**Comment by contigiani** [comment]
Oops, my mistake -- thanks for letting me know!

**Comment by jobovy** [comment]
No problem, thanks!
